name: Expressions
  on: 
    workflow_dispatch:
        inputs:
          edad:
            description: 'Edad'
            type: integer
            required: true
          nombre:
            description: 'Nombre'
            type: string
            required: true
            default: 'Javier'
   jobs:
     mayor:
       if: ${{inputs.edad >= 18}} 
         runs-on: ubuntu-latest
         steps: 
             name: Correr Script
             - run: echo ${{ inputs.edad }} es Mayor de edad

        if: ${{inputs.edad < 18}} 
         runs-on: ubuntu-latest
         steps: 
             name: Correr Script
             - run: echo ${{ inputs.edad }} es Menor de edad 
      
     
            
            
  
