name: Variables y secrets
run-name: Aprendiendo a usar Github actions secrets
on:
  workflow_dispatch:
env:
  name: Javier Guevara
  dia: Lunes
jobs:
  saludando:
    runs-on: ubuntu-latest
    steps:
      - name: Correr Script
        run: echo Saludos ${{ env.name }} es el día ${{ env.dia }}
  saludando-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Correr Script secrets
        run: echo Saludos ${{ env.name }} tu password es ${{ secrets.TEST_PASSWORD }}
